<a href="https://colab.research.google.com/github/brennomongero/alura-git/blob/master/Regress%C3%A3o_com_Dummies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import pyarrow.feather as feather
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [25]:
corrupcao = pd.read_feather('corrupcao.feather')
corrupcao

              pais  cpi          regiao
0        Argentina  3.9  América do Sul
1        Australia  8.7         Oceania
2          Austria  7.9          Europa
3          Belgium  7.1          Europa
4           Brazil  4.0  América do Sul
5           Canada  8.9    EUA e Canadá
6            Chile  6.2  América do Sul
7            China  2.5            Ásia
8         Colombia  4.0  América do Sul
9           Cyprus  6.3          Europa
10      Czech Rep.  4.6          Europa
11         Denmark  9.3          Europa
12           Egypt  2.1            Ásia
13          France  6.8          Europa
14         Germany  7.9          Europa
15          Greece  3.5          Europa
16         Iceland  8.5          Europa
17           India  2.3            Ásia
18       Indonesia  1.8            Ásia
19         Ireland  8.0          Europa
20           Italy  3.9          Europa
21      Kazakhstan  1.9            Ásia
22          Kuwait  2.8            Ásia
23         Lebanon  1.5            Ásia
24        Malaysia  3.4            Ásia
25     Netherlands  8.8          Europa
26     New Zealand  9.3         Oceania
27          Norway  8.6          Europa
28            Oman  3.3            Ásia
29     Philippines  1.4            Ásia
30          Poland  5.3          Europa
31        Portugal  6.0          Europa
32         Romania  3.7          Europa
33          Russia  2.1          Europa
34    Saudi Arabia  3.7            Ásia
35          Serbia  3.5          Europa
36    South Africa  2.8            Ásia
37           Spain  6.1          Europa
38          Sweden  9.2          Europa
39     Switzerland  8.7          Europa
40          Taiwan  3.8            Ásia
41        Thailand  2.5            Ásia
42          Turkey  4.4          Europa
43         Ukraine  2.4          Europa
44  United Kingdom  7.6          Europa
45   United States  7.1    EUA e Canadá
46       Venezuela  2.8  América do Sul
47          Jordan  2.0            Ásia
48           Syria  1.0            Ásia
49            Iraq  0.8            Ásia

In [26]:
corrupcao.describe(include='all')

             pais        cpi  regiao
count          50  50.000000      50
unique         50        NaN       5
top     Argentina        NaN  Europa
freq            1        NaN      24
mean          NaN   4.894000     NaN
std           NaN   2.678974     NaN
min           NaN   0.800000     NaN
25%           NaN   2.575000     NaN
50%           NaN   3.950000     NaN
75%           NaN   7.475000     NaN
max           NaN   9.300000     NaN

In [29]:
corrupcao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pais    50 non-null     object
 1   cpi     50 non-null     float64
 2   regiao  50 non-null     category
dtypes: category(1), float64(1), object(1)
memory usage: 1.2+ KB

In [30]:
corrupcao.regiao.value_counts()

Europa            24
Ásia              17
América do Sul     5
Oceania            2
EUA e Canadá       2
Name: regiao, dtype: int64

In [56]:
#Criando Dummies
corrupcao_dummies = pd.concat([corrupcao, pd.get_dummies(corrupcao['regiao'],)], axis=1).drop(columns=['regiao'])
corrupcao_dummies = corrupcao_dummies.drop(columns=[corrupcao['regiao'].value_counts().idxmax()])
corrupcao_dummies.rename(columns={
      "América do Sul": 'America_do_sul',
      "EUA e Canadá" : 'EUA_Canada',
      "Ásia": "Asia"}, inplace = True)
corrupcao_dummies

              pais  cpi  America_do_sul  Oceania  EUA_Canada  Asia
0        Argentina  3.9               1        0           0     0
1        Australia  8.7               0        1           0     0
2          Austria  7.9               0        0           0     0
3          Belgium  7.1               0        0           0     0
4           Brazil  4.0               1        0           0     0
5           Canada  8.9               0        0           1     0
6            Chile  6.2               1        0           0     0
7            China  2.5               0        0           0     1
8         Colombia  4.0               1        0           0     0
9           Cyprus  6.3               0        0           0     0
10      Czech Rep.  4.6               0        0           0     0
11         Denmark  9.3               0        0           0     0
12           Egypt  2.1               0        0           0     1
13          France  6.8               0        0           0     0
14         Germany  7.9               0        0           0     0
15          Greece  3.5               0        0           0     0
16         Iceland  8.5               0        0           0     0
17           India  2.3               0        0           0     1
18       Indonesia  1.8               0        0           0     1
19         Ireland  8.0               0        0           0     0
20           Italy  3.9               0        0           0     0
21      Kazakhstan  1.9               0        0           0     1
22          Kuwait  2.8               0        0           0     1
23         Lebanon  1.5               0        0           0     1
24        Malaysia  3.4               0        0           0     1
25     Netherlands  8.8               0        0           0     0
26     New Zealand  9.3               0        1           0     0
27          Norway  8.6               0        0           0     0
28            Oman  3.3               0        0           0     1
29     Philippines  1.4               0        0           0     1
30          Poland  5.3               0        0           0     0
31        Portugal  6.0               0        0           0     0
32         Romania  3.7               0        0           0     0
33          Russia  2.1               0        0           0     0
34    Saudi Arabia  3.7               0        0           0     1
35          Serbia  3.5               0        0           0     0
36    South Africa  2.8               0        0           0     1
37           Spain  6.1               0        0           0     0
38          Sweden  9.2               0        0           0     0
39     Switzerland  8.7               0        0           0     0
40          Taiwan  3.8               0        0           0     1
41        Thailand  2.5               0        0           0     1
42          Turkey  4.4               0        0           0     0
43         Ukraine  2.4               0        0           0     0
44  United Kingdom  7.6               0        0           0     0
45   United States  7.1               0        0           1     0
46       Venezuela  2.8               1        0           0     0
47          Jordan  2.0               0        0           0     1
48           Syria  1.0               0        0           0     1
49            Iraq  0.8               0        0           0     1

In [57]:
# Estimar o modelo de regressão múltipla com intercepto automático
modelo_paises = smf.ols(formula='cpi ~ America_do_sul+Oceania+EUA_Canada+Asia', data=corrupcao_dummies).fit()
modelo_paises.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    cpi   R-squared:                       0.603
Model:                            OLS   Adj. R-squared:                  0.568
Method:                 Least Squares   F-statistic:                     17.09
Date:                Mon, 24 Jul 2023   Prob (F-statistic):           1.37e-08
Time:                        19:53:33   Log-Likelihood:                -96.620
No. Observations:                  50   AIC:                             203.2
Df Residuals:                      45   BIC:                             212.8
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          6.2583      0.360     17.406      0.000       5.534       6.983
America_do_sul    -2.0783      0.866     -2.400      0.021      -3.822      -0.334
Oceania            2.7417      1.296      2.115      0.040       0.131       5.353
EUA_Canada         1.7417      1.296      1.343      0.186      -0.869       4.353
Asia              -3.9289      0.558     -7.036      0.000      -5.054      -2.804
==============================================================================
Omnibus:                        1.205   Durbin-Watson:                   1.928
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                1.083
Skew:                          -0.347   Prob(JB):                        0.582
Kurtosis:                       2.804   Cond. No.                         5.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""